version: 0.2

phases:
  install:
    commands:
      - echo "Nothing to install."
  build:
    commands:
      - echo Build started on `date`
      - cd lambda
      - python ../zipdir.py Contents.zip project-dir
      - python ../zip.py ../Hello_Intent.zip Contents.zip hello_intent.py bibot_config.py bibot_helpers.py bibot_userexits.py
      - python ../zip.py ../Goodbye_Intent.zip goodbye_intent.py bibot_config.py bibot_helpers.py bibot_userexits.py
      - python ../zip.py ../SelectCategory_Intent.zip selectcategory_intent.py bibot_config.py bibot_helpers.py bibot_userexits.py
      - python ../zip.py ../GetDimension_Intent.zip getdimension_intent.py bibot_config.py bibot_helpers.py bibot_userexits.py
      - cd ..
      - ls -l *.zip
      - bash delete.sh
   #   - bash build-db.sh  , Unnecessary since we aren't using any DB yet.
      - bash build-bot.sh
  post_build:
    commands:
      - echo Build completed on `date`

